name: Pylint

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.8", "3.9", "3.10"]
    steps:
    - name: checkout code
      uses: actions/checkout@v4

    - name: set up python
      uses: actions/setup-python@v5
      with:
        python-python-version: '3.11' # or whatever version your setup runs on

    - name: install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: run pylint gatekeeper
      run: |
        pip install pylint
        pylint bot.py
